kind: Pod
apiVersion: v1
metadata:
  name: multi-container
spec:
  containers:
  - name: container-1
    image: nginx
  - name: container-2
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while :; do echo 'welcome'; sleep 5; done"]
